# pull the official base image
FROM node:22.16.0-alpine
ENV NODE_ENV development
# set working direction
WORKDIR /app
# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
# Cache and Install dependencies
COPY package*.json yarn.lock ./
RUN yarn install
# copy app files
COPY . ./
# Expose port
EXPOSE 3100
# start the app

CMD [ "yarn", "run", "dev" ]