services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db_resotre
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: gowtampaul1995@
      POSTGRES_DB: generative_ai_app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main_network
  restore:
    image: postgres:16-alpine
    container_name: postgres_restore
    volumes:
      - ./backups:/backups # Mount backup directory
      - ./scripts/restore.sh:/restore.sh # Mount restore script
    entrypoint: ["sh", "/restore.sh"] # Execute the restore script
    environment:
      PGPASSWORD: gowtampaul1995@ # PostgreSQL password
    depends_on:
      - postgres
    networks:
      - main_network

networks:
  main_network:
    driver: bridge

volumes:
  postgres_data:
