services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: gowtampaul1995@
      POSTGRES_DB: generative_ai_app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main_network
  backup:
    image: postgres:16-alpine
    container_name: db_backup
    entrypoint: ["sh", "-c", "/backup.sh"]
    volumes:
      - ./backups:/backups # Mount local folder to store backups
      - ./scripts/backup.sh:/backup.sh
    environment:
      PGPASSWORD: gowtampaul1995@ # match your DB password
    depends_on:
      - postgres
    networks:
      - main_network
networks:
  main_network:
    driver: bridge

volumes:
  postgres_data:
